version: '3'

services:
  app:
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    volumes:
      - ./.pdbrc.py:/home/sivpack/.pdbrc.py
