"""Create movie and rating tables

Revision ID: a516a8e94fbb
Revises: 82cd558300d4
Create Date: 2018-07-01 22:41:00.287238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a516a8e94fbb"
down_revision = "82cd558300d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("movie_id", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movie.id"], name="fk_rating_movie_id"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="fk_rating_user_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rating")
    op.drop_table("movie")
    # ### end Alembic commands ###
